class: base--STYLED
colors: 5

images:
  - images/pattern01.jpg: Decorative screen
  - images/pattern02.jpg: Decorative screen
  - images/pattern03.jpg: Black and white
  - images/pattern04.jpg: Blue tint
  - images/icon_druplicon_blue_dark.svg: Solid icon
  - images/pattern05.png: Partner ad
  - images/pattern06.png: Partner ad
descriptors:
  - Oh Wow
  - Such Movement
  - Many Styles
  - Great Abstract

