class: base--STYLED
colors: 5

images:
  - images/pattern01.jpg: Decorative screen
  - images/pattern02.jpg: Decorative screen
  - images/pattern03.jpg: Black and white
  - images/pattern04.jpg: Blue tint
  - images/icon_druplicon_blue_dark.svg: Solid icon
  - images/logo-sample_Lead.svg: Lead partner logo
  - images/logo-sample_Core.svg: Core partner logo
  - images/logo-sample_Contribute.svg: Contributing partner logo
  - images/logo-sample_Support.svg: Supporting partner logo
  - images/logo-sample_Community.svg: Community partner logo
descriptors:
  - Oh Wow
  - Such Movement
  - Many Styles
  - Great Abstract

